name: Dart pub publish --dry-run, Publishing Preview for PRs
on:
  pull_request:
    branches:
      - releases
jobs:
  preview-publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze
        if: always()

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs
        if: always()

      - name: Preview publish package (dry-run)
        run: dart pub publish --dry-run
