name: Dart Unit Tests for PRs

on:
  workflow_dispatch:
  pull_request:
    branches: ["**"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart --version
      - run: dart pub get
#      - run: dart format --output=none --set-exit-if-changed ./ # FIXME https://github.com/dartclub/turf_dart/pull/248

      - name: Analyze Project
        run: dart analyze
        if: always()

      - name: Run tests with coverage enabled
        run: dart test --coverage=.artefacts/coverage
        if: always()

      - name: Archive raw coverage artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: raw-coverage
          path: .artefacts/coverage
